### ISSUE TITLE
User can register domain without giving permissions to the dapp

### ISSUE THREAD

**Issue by asemiankevich** [status-im/ens-usernames#57] opened 2018-10-12 11:17 UTC
1. Open status
2. Open ens dapp
3. Search for some free domain
4. Tap register with transaction and proceed

Expected: 
1. user should be asked about permissions before registering the domain
2. if i granted the dapp with permissions on a device and then created new account in status - user should be asked about permissions again

**Comment by rachelhamlin** [comment] 2018-10-12 19:46
Actually not a bug - there should be a `Grant access` CTA in the chat ID box, and only if a user taps on that are they prompted to grant profile permissions. 

See this issue - https://github.com/status-im/ens-usernames/issues/38 

Closing for now; we can discuss if this should be change during phase 2.

**Closed by rachelhamlin** 2018-10-12 19:46 UTC
Labels: bug, v1 launch
